--Exercício 1

SELECT * FROM  VEM_SER.PESSOA WHERE ID_PESSOA =:1 AND CPF =:2; --Comando do DBeaver

SELECT * FROM dual;


CREATE TABLE VEM_SER.PAIS(
	id_pais NUMBER(38) PRIMARY KEY NOT NULL,
	nome VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE VEM_SER.ESTADO(
	id_estado NUMBER(38) PRIMARY KEY NOT NULL,
	id_pais NUMBER(38) NOT NULL,
	nome VARCHAR(50),
	CONSTRAINT FK_id_pais FOREIGN KEY (id_pais) REFERENCES pais(id_pais)
);

DROP TABLE PAIS;
DROP TABLE ESTADO
DROP TABLE ENDERECO 
DROP TABLE CIDADE;
DROP TABLE "BAIRRO"; 


CREATE TABLE Endereco (
                ID_ENDERECO NUMBER(38) NOT NULL,
                ID_BAIRRO NUMBER(38) NOT NULL,
                ID_CIDADE NUMBER(38) NOT NULL,
                LOGRADOURO VARCHAR2(255) NOT NULL,
                NUMERO VARCHAR2(38) NOT NULL,
                COMPLEMENTO VARCHAR2(100),
                CEP CHAR(9),
                PRIMARY KEY (ID_ENDERECO),
                CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY (ID_BAIRRO, ID_CIDADE) REFERENCES BAIRRO (ID_BAIRRO, ID_CIDADE)
                
);

CREATE TABLE VEM_SER.BAIRRO(
	id_bairro NUMBER(38) NOT NULL,
	id_cidade NUMBER(38) NOT NULL,
	id_estado NUMBER(38) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID_BAIRRO, ID_CIDADE),
	CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY (ID_CIDADE, ID_ESTADO) REFERENCES CIDADE (ID_CIDADE, ID_ESTADO)
);

CREATE TABLE VEM_SER.CIDADE(
	id_cidade NUMBER(38) NOT NULL,
	id_estado NUMBER(38) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID_CIDADE, ID_ESTADO),
	CONSTRAINT FK_id_estado FOREIGN KEY (id_estado) REFERENCES estado(id_estado)
);

--Exercício 2

ALTER TABLE "Estado" ADD CONSTRAINT "Estado_fk0" FOREIGN KEY ("id_pais") REFERENCES "Pais"("id_pais");

ALTER TABLE "Cidade" ADD CONSTRAINT id_cidade PRIMARY KEY REFERENCES (id_cidade, id_estado);

ALTER TABLE "Bairro" ADD CONSTRAINT "Bairro_fk0" FOREIGN KEY ("id_cidade") REFERENCES "Cidade"("id_cidade");

ALTER TABLE "Endereco" ADD CONSTRAINT "Endereco_fk0" FOREIGN KEY ("id_bairro") REFERENCES "Bairro"("id_bairro");

CREATE SEQUENCE VEM_SER.SEQ_PAIS
START WITH 1
INCREMENT BY 1
nocache nocycle;

INSERT INTO VEM_SER.PAIS 
(ID_PAIS, NOME)
VALUES(seq_pais.nextval, 'Brasil');

INSERT INTO VEM_SER.PAIS 
(ID_PAIS, NOME)
VALUES(seq_pais.nextval, 'Argentina');

CREATE SEQUENCE VEM_SER.SEQ_ESTADO
START WITH 1
INCREMENT BY 1
nocache nocycle;

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(seq_estado.nextval, 1, 'Bahia');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(seq_estado.nextval, 1, 'Distrito Federal');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(seq_estado.nextval, 2, 'Rio Grande do Sul');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(seq_estado.nextval, 2, 'Santa Catarina');


CREATE SEQUENCE VEM_SER.SEQ_CIDADE
START WITH 1
INCREMENT BY 1
nocache nocycle;

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_cidade.nextval, 1, 'São Gabriel');

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_cidade.nextval, 1, 'Salvador');

CREATE SEQUENCE VEM_SER.SEQ_BAIRRO
START WITH 1
INCREMENT BY 1
nocache nocycle;

INSERT INTO VEM_SER.BAIRRO  
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_bairro.nextval, 1, 1, 'Maria Candida');

INSERT INTO VEM_SER.BAIRRO  
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_bairro.nextval, 2, 1, 'Avenida Rui Barbosa');

CREATE SEQUENCE VEM_SER.SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
nocache nocycle;

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 1, 1, 'Rua Presidente Dutra', '11A', 'Esquina com Adalberto', '44915-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 3, 2, 'Avenida Salvador', '1565', 'Apartamento', '44200-000');

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_cidade.nextval, 2, 'Porto Alegre');

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_cidade.nextval, 2, 'Caxias');

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_cidade.nextval, 3, 'Ceilândia');

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_cidade.nextval, 3, 'Brasília');

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_cidade.nextval, 4, 'Florianópolis');

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_cidade.nextval, 4, 'São Jose');

INSERT INTO VEM_SER.BAIRRO  
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_bairro.nextval, 3, 2, 'Baixo do Rio');

INSERT INTO VEM_SER.BAIRRO  
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_bairro.nextval, 4, 2, 'Alvorada');

INSERT INTO VEM_SER.BAIRRO  
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_bairro.nextval, 5, 3, 'Sul');

INSERT INTO VEM_SER.BAIRRO  
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_bairro.nextval, 6, 3, 'Plano');

INSERT INTO VEM_SER.BAIRRO  
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_bairro.nextval, 7, 4, 'Campesche');

INSERT INTO VEM_SER.BAIRRO  
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(seq_bairro.nextval, 8, 4, 'Centro');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 1, 1, 'Rua Barreto Rocha', '55B', 'Esquina com Adalberto', '44915-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 3, 2, 'Passo Fundo', '135', '', '55900-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 4, 3, 'Alto Rio', '545', 'Centro', '55915-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 4, 3, 'Sul do Sul', '17A', 'Alvorada do Sul', '55915-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 5, 4, 'Norte de Brigadeiro', '915', 'Duque de Ferraz', '55815-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 5, 4, 'Norte de Brigadeiro2', '548', 'Centro', '55815-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 6, 5, 'QNN 10 Conjunto H', '20', 'Sul', '72220-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 6, 5, 'SHS', '38', 'Asa Sul', '70210-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 7, 6, 'SHSN', '126', 'Asa Sul', '71250-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 7, 6, 'SPW', '12564', 'Park Way', '70120-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 8, 7, 'Avenida dos Mares', '123', 'Centro Campesche', '65000-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 8, 7, 'Avenida das Marés', '321', 'Centro Campesche', '65978-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 9, 8, 'Rua Mario Oswaldo', '719', 'Do lado da Avenida Itaguaçu', '65745-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 9, 8, 'Rua Oswaldino', '346', 'Do lado da serrinha', '65015-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 9, 8, 'avenida Dino', '396', 'Do lado da serrinha', '65123-000');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(seq_endereco.nextval, 6, 5, 'QNP 35, Conjunto P', '55', 'P-Sul', '75123-002');

SELECT * FROM PAIS;
SELECT * FROM ESTADO;
SELECT * FROM CIDADE;
SELECT * FROM BAIRRO;
SELECT * FROM ENDERECO

SELECT nome FROM PAIS 
ORDER BY nome DESC;

SELECT logradouro, cep FROM ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'A%';

SELECT logradouro, cep FROM ENDERECO
WHERE cep  LIKE '%0';

SELECT * FROM ENDERECO
WHERE NUMERO BETWEEN 1 AND 100;

SELECT * FROM ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'RUA%';

SELECT COUNT(ID_ENDERECO) FROM ENDERECO;

SELECT logradouro, cep FROM ENDERECO
ORDER BY ID_ENDERECO


