-- Homework3

SELECT * FROM PESSOA

SELECT *
FROM PESSOA P
RIGHT OUTER JOIN 
	CONTATO c ON p.id_pessoa = c.id_pessoa

SELECT *
FROM PESSOA P
RIGHT OUTER JOIN 
	PESSOA_X_PESSOA_ENDERECO pxpe ON p.id_pessoa = PXPE.id_pessoa
	RIGHT OUTER JOIN
	ENDERECO_PESSOA ep e ON ep.id_endereco = PXPE.id_endereco

SELECT *
FROM PESSOA p
RIGHT OUTER JOIN
	CONTATO c ON p.ID_PESSOA = c.ID_PESSOA
	RIGHT OUTER JOIN
	PESSOA_X_PESSOA_ENDERECO pxpe ON p.id_pessoa = PXPE.id_pessoa
	RIGHT OUTER JOIN
	ENDERECO_PESSOA ep ON ep.id_endereco = pxpe.ID_ENDERECO
	
SELECT *
FROM PESSOA P
FULL OUTER JOIN
	CONTATO c ON p.id_pessoa = c.ID_PESSOA;
	
SELECT *
FROM PESSOA P
FULL OUTER JOIN 
	PESSOA_X_PESSOA_ENDERECO pxpe ON p.id_pessoa = PXPE.id_pessoa
	FULL OUTER JOIN
	ENDERECO_PESSOA ep ON ep.ID_ENDERECO = PXPE.id_endereco
	
SELECT p.NOME, E.LOGRADOURO 
FROM PESSOA p
FULL OUTER JOIN
	CONTATO c ON p.ID_PESSOA = c.ID_PESSOA
	FULL OUTER JOIN
	PESSOA_X_PESSOA_ENDERECO pxpe ON p.id_pessoa = PXPE.id_pessoa
	FULL OUTER JOIN
	ENDERECO E ON e.id_endereco = pxpe.ID_ENDERECO
	
SELECT *
FROM ENDERECO e
WHERE EXISTS 
	(SELECT * FROM PESSOA p WHERE p.ID_PESSOA = e.ID_ENDERECO)
	
SELECT *
FROM PESSOA p
WHERE EXISTS 
	(SELECT logradouro FROM ENDERECO e WHERE p.ID_PESSOA = e.ID_ENDERECO)
	
SELECT p.id_pessoa, p.NOME, e.ID_ENDERECO, e.LOGRADOURO 
FROM PESSOA p
INNER JOIN
	ENDERECO e ON p.ID_PESSOA = e.ID_ENDERECO
	
