CREATE TABLE vem_ser.estudante(
	id_estudante NUMBER NOT NULL,
	nome VARCHAR2(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER (10) UNIQUE NOT NULL,
	ativo CHAR(1),
	PRIMARY KEY(id_estudante)
);

DROP SEQUENCE VEM_SER.SEQ_ESTUDANTE;

CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
nocache nocycle;

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Paulo', '12/08/1986', 154851, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Rafael', '12/10/1988', 154852, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Maicon', '12/02/1987', 154853, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Roberto', '05/01/1986', 154854, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'João', '31/01/2000', 154855, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Ester', '14/10/2001', 154856, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Francisco', '25/10/2002', 154857, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Maria', '12/08/1987', 154858, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Junior', '27/07/1986', 154859, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'José', '13/05/1977', 154860, 'S');

SELECT * FROM ESTUDANTE;

DROP TABLE estudante;

